### ISSUE TITLE
do not hardcode nginx version

### ISSUE THREAD

**Issue by arosenhagen** [gchef/nginx-cookbook#13]
since the cookbook should work across nginx versions, it'll make sense to set the version as default value (not implicitly)

``` ruby
default[:nginx][:version] = "1.2.4"
```

so we can override this value with

``` ruby
node.set[:nginx][:version] = "1.2.6"
```

**Comment by gerhard** [comment]
I've used set explicitly because I'm re-using the version for the source. If this was overwritten, the source would not pick up on it - unless I've missed something.

**Comment by arosenhagen** [comment]
I like to use the nginx cookbook as part of another cookbook. In my understanding if you just write

``` ruby
default[:nginx][:version] = "1.2.4"
```

in attributes/default.rb
I can then overwrite the value in my cookbook with 

``` ruby
node.set[:nginx][:version] = "1.2.6"
```

Unless the value gets overwritten it uses the default value of your cookboook (and of course the source will pick up on whatever version the variable has)

**Comment by gerhard** [comment]
In my tests, [this line](https://github.com/gchef/nginx-cookbook/blob/master/attributes/default.rb#L2) will not be aware of `[:nginx][:version]` overwrites and will use the attributes' default value. The alternative would be to work out the source URI last minute, after all version overwrites have been applied, not directly in attributes. I'll try it next time I go over this code.
